# Generated by Django 5.1.1 on 2024-10-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='foodcategory_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodcategory_name', models.CharField(max_length=100)),
                ('foodcategory_image', models.ImageField(upload_to='media/')),
                ('foodcategory_price', models.IntegerField(max_length=100)),
                ('foodcategory_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foods')),
            ],
        ),
    ]
