# Generated by Django 5.1.1 on 2024-10-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='foodcategory',
        ),
        migrations.AddField(
            model_name='foods',
            name='iamge',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='foods',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
