# Generated by Django 5.1.1 on 2024-10-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_foods_foodcategory_foods_iamge_foods_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory_items',
            name='foodcategory_description',
            field=models.TextField(default='', max_length=700),
        ),
    ]
