# Generated by Django 5.1.1 on 2024-10-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_foodcategory_items_foodcategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefs_image', models.ImageField(upload_to='media/')),
                ('chefs_name', models.CharField(max_length=100)),
                ('chefs_post', models.CharField(max_length=100)),
                ('chefs_socialmedia', models.URLField()),
            ],
        ),
    ]
