# Generated by Django 5.1.1 on 2024-10-10 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_chefs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foodcategory_items')),
            ],
        ),
        migrations.CreateModel(
            name='Weeklyoffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.foodcategory_items')),
            ],
        ),
    ]
